import Link from "next/link";
import { ClipboardList, Filter, ShieldCheck } from "lucide-react";
import { requirePermission } from "@/core/admin/admin-service";
import { listAuditLogs } from "@/core/admin/audit-service";

const formatter = new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Bahia", dateStyle: "short", timeStyle: "medium" });
const actionLabels: Record<string, string> = { "user.profile_updated": "Perfil atualizado", "user.plan_changed": "Plano do usuário alterado", "user.disabled": "Usuário desativado", "user.enabled": "Usuário reativado", "user.password_reset_link_generated": "Link de senha gerado", "clinical_case.created": "Caso clínico criado", "clinical_case.status_changed": "Status do caso alterado", "plan.updated": "Plano atualizado", "staff.role_changed": "Papel administrativo alterado", "site_content.updated": "SEO e conteúdo atualizados" };
const targetLabels: Record<string, string> = { user: "Usuário", clinicalCase: "Caso clínico", clinical_case: "Caso clínico", plan: "Plano", staff: "Administrador", siteContent: "SEO e conteúdo" };

export default async function AuditPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requirePermission("audit.read");
  const params = await searchParams;
  const read = (key: string) => typeof params[key] === "string" ? params[key] : "";
  const result = await listAuditLogs({ category: read("categoria"), actor: read("responsavel"), search: read("busca"), from: read("inicio"), to: read("fim"), page: Number(read("pagina")) || 1 });
  const pageHref = (page: number) => { const query = new URLSearchParams(); for (const key of ["categoria", "responsavel", "busca", "inicio", "fim"]) if (read(key)) query.set(key, read(key)); query.set("pagina", String(page)); return `/admin/auditoria?${query}`; };
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
    <header><div className="inline-flex rounded-full bg-primary/15 px-3 py-1 text-xs font-extrabold uppercase tracking-wider text-primary">Segurança e governança</div><h1 className="mt-3 text-4xl font-black">Auditoria</h1><p className="mt-1 font-bold text-muted-foreground">Histórico imutável das ações administrativas realizadas na plataforma.</p></header>
    <section className="grid gap-3 sm:grid-cols-2"><article className="card-pop p-5"><ClipboardList className="h-5 w-5 text-primary" /><p className="mt-2 text-3xl font-black">{result.total}</p><p className="text-xs font-extrabold uppercase text-muted-foreground">Registros encontrados</p></article><article className="card-pop p-5"><ShieldCheck className="h-5 w-5 text-primary" /><p className="mt-2 text-3xl font-black">{result.actors.length}</p><p className="text-xs font-extrabold uppercase text-muted-foreground">Responsáveis identificados</p></article></section>
    <form className="card-pop grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-[1fr_11rem_13rem_10rem_10rem_auto]">
      <input name="busca" defaultValue={read("busca")} placeholder="Ação ou ID do alvo" className="h-11 rounded-xl border-2 border-border bg-background px-3 text-sm font-bold outline-none focus:border-primary" />
      <select name="categoria" defaultValue={read("categoria")} aria-label="Categoria" className="h-11 rounded-xl border-2 border-border bg-background px-3 text-sm font-bold"><option value="">Todas as áreas</option><option value="user">Usuários</option><option value="clinicalCase">Casos clínicos</option><option value="plan">Planos</option><option value="siteContent">SEO e conteúdo</option><option value="staff">Administradores</option></select>
      <select name="responsavel" defaultValue={read("responsavel")} aria-label="Responsável" className="h-11 rounded-xl border-2 border-border bg-background px-3 text-sm font-bold"><option value="">Todos os responsáveis</option>{result.actors.map((item) => <option key={item.uid} value={item.uid}>{item.name}</option>)}</select>
      <label className="text-[10px] font-extrabold uppercase text-muted-foreground">De<input type="date" name="inicio" defaultValue={read("inicio")} className="mt-1 h-8 w-full rounded-lg border border-border bg-background px-2 text-xs text-foreground" /></label>
      <label className="text-[10px] font-extrabold uppercase text-muted-foreground">Até<input type="date" name="fim" defaultValue={read("fim")} className="mt-1 h-8 w-full rounded-lg border border-border bg-background px-2 text-xs text-foreground" /></label>
      <button className="btn-pop h-11 gap-2 bg-primary px-5 text-xs text-primary-foreground shadow-[var(--shadow-pop)]"><Filter className="h-4 w-4" />Filtrar</button>
    </form>
    {result.truncated && <p className="rounded-xl bg-xp/15 px-4 py-3 text-sm font-bold text-foreground">A visualização está limitada aos 1.000 registros mais recentes.</p>}
    <section className="card-pop overflow-hidden"><div className="hidden grid-cols-[11rem_1fr_12rem_13rem] gap-4 border-b-2 border-border bg-muted/50 px-5 py-3 text-xs font-extrabold uppercase tracking-wider text-muted-foreground md:grid"><span>Data</span><span>Ação</span><span>Responsável</span><span>Alvo</span></div>
      {result.logs.length ? <div className="divide-y-2 divide-border">{result.logs.map((log) => <details key={log.id} className="group"><summary className="grid cursor-pointer list-none gap-2 px-5 py-4 transition hover:bg-muted/40 md:grid-cols-[11rem_1fr_12rem_13rem] md:items-center md:gap-4"><span className="text-xs font-bold text-muted-foreground">{log.createdAt ? formatter.format(new Date(log.createdAt)) : "Sem data"}</span><span className="font-extrabold">{actionLabels[log.action] ?? log.action}</span><span className="truncate text-xs font-bold">{log.actorName}</span><span className="min-w-0 text-xs"><b>{targetLabels[log.targetType] ?? log.targetType}</b><span className="block truncate text-muted-foreground">{log.targetName ?? log.targetId}</span></span></summary><div className="border-t border-border bg-muted/25 px-5 py-5"><div className="grid gap-4 lg:grid-cols-2"><AuditValue label="Antes" value={log.before} /><AuditValue label="Depois" value={log.after} /></div><p className="mt-4 break-all text-[10px] font-bold text-muted-foreground">Registro: {log.id} · Alvo: {log.targetId || "—"} · Responsável: {log.actorUid || "Sistema"}</p></div></details>)}</div> : <div className="grid place-items-center px-5 py-16 text-center"><ClipboardList className="h-10 w-10 text-muted-foreground/40" /><p className="mt-3 font-extrabold">Nenhum registro encontrado</p><p className="text-sm font-bold text-muted-foreground">Revise os filtros utilizados.</p></div>}
    </section>
    <nav aria-label="Paginação" className="flex items-center justify-between"><p className="text-sm font-bold text-muted-foreground">Página {result.page} de {result.totalPages}</p><div className="flex gap-2">{result.page > 1 && <Link href={pageHref(result.page - 1)} className="btn-pop bg-muted px-4 py-2 text-xs shadow-[var(--shadow-pop-muted)]">Anterior</Link>}{result.page < result.totalPages && <Link href={pageHref(result.page + 1)} className="btn-pop bg-primary px-4 py-2 text-xs text-primary-foreground shadow-[var(--shadow-pop)]">Próxima</Link>}</div></nav>
  </main>;
}

function AuditValue({ label, value }: { label: string; value: unknown }) { return <div><p className="mb-2 text-xs font-extrabold uppercase text-muted-foreground">{label}</p><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-words rounded-xl border border-border bg-background p-4 text-xs font-medium">{value === null ? "Sem dados" : JSON.stringify(value, null, 2)}</pre></div>; }
