"use client";

import { useState } from "react";
import { LoaderCircle, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { readApiResponse } from "@/presentation/http/read-api-response";

export function CancelSubscription() {
  const [open, setOpen] = useState(false); const [pending, setPending] = useState<"period_end" | "refund" | null>(null); const [error, setError] = useState(""); const router = useRouter();
  async function cancel(mode: "period_end" | "refund") { setPending(mode); setError(""); const response = await fetch("/api/billing/cancel", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode }) }); const payload = await readApiResponse<{ message?: string; error?: string }>(response); if (!response.ok) { setError(payload.error || "Não foi possível cancelar."); setPending(null); return; } setOpen(false); setPending(null); router.refresh(); }
  return <>{<button type="button" onClick={() => setOpen(true)} className="text-sm font-extrabold text-destructive hover:underline">Cancelar plano</button>}{open && <div role="dialog" aria-modal="true" aria-labelledby="cancel-title" className="fixed inset-0 z-[100] grid place-items-center bg-foreground/45 p-4 backdrop-blur-sm"><section className="card-pop relative w-full max-w-lg p-6 sm:p-8"><button type="button" onClick={() => setOpen(false)} aria-label="Fechar" className="absolute right-4 top-4 grid h-9 w-9 place-items-center rounded-full bg-muted"><X className="h-4 w-4" /></button><h2 id="cancel-title" className="pr-10 text-2xl font-black">Como deseja cancelar?</h2><p className="mt-2 text-sm font-bold text-muted-foreground">Escolha entre manter o acesso até o fim do ciclo já pago ou solicitar cancelamento imediato com reembolso.</p><div className="mt-6 grid gap-3"><button disabled={Boolean(pending)} onClick={() => cancel("period_end")} className="rounded-2xl border-2 border-primary/30 bg-primary/10 p-4 text-left transition hover:border-primary disabled:opacity-60"><strong className="block">Manter até o fim do ciclo</strong><span className="mt-1 block text-xs font-bold text-muted-foreground">Interrompe as próximas cobranças e preserva seu acesso pelo período atual.</span>{pending === "period_end" && <LoaderCircle className="mt-2 h-4 w-4 animate-spin" />}</button><button disabled={Boolean(pending)} onClick={() => cancel("refund")} className="rounded-2xl border-2 border-destructive/25 bg-destructive/5 p-4 text-left transition hover:border-destructive disabled:opacity-60"><strong className="block text-destructive">Cancelar agora e solicitar reembolso</strong><span className="mt-1 block text-xs font-bold text-muted-foreground">Disponível somente até 7 dias corridos após o pagamento.</span>{pending === "refund" && <LoaderCircle className="mt-2 h-4 w-4 animate-spin" />}</button></div>{error && <p role="alert" className="mt-4 text-sm font-extrabold text-destructive">{error}</p>}</section></div>}</>;
}
