"use client";

import { useActionState } from "react";
import { LoaderCircle, Save, TicketPercent } from "lucide-react";
import { saveCouponAction, type CouponActionState } from "./actions";

const field = "mt-1.5 h-11 w-full rounded-xl border-2 border-border bg-background px-3 text-sm font-bold outline-none focus:border-primary";
export function CouponForm() {
  const [state, action, pending] = useActionState(saveCouponAction, {} as CouponActionState);
  return <form action={action} className="card-pop space-y-5 p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/15 text-primary"><TicketPercent className="h-5 w-5" /></span><div><h2 className="text-xl font-black">Criar ou atualizar cupom</h2><p className="text-sm font-bold text-muted-foreground">Use o mesmo código para atualizar uma campanha existente.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-extrabold">Código<input name="code" required minLength={3} maxLength={30} placeholder="BEMVINDO20" className={`${field} uppercase`} /></label><label className="text-sm font-extrabold">Descrição<input name="description" required maxLength={140} placeholder="Campanha de boas-vindas" className={field} /></label><label className="text-sm font-extrabold">Tipo de desconto<select name="discountType" defaultValue="percent" className={field}><option value="percent">Percentual (%)</option><option value="fixed">Valor fixo (R$)</option></select></label><label className="text-sm font-extrabold">Valor<input name="discountValue" type="number" min="0.01" max="100000" step="0.01" required className={field} /></label><label className="text-sm font-extrabold">Limite de usos<input name="maxRedemptions" type="number" min="0" max="1000000" defaultValue="0" required className={field} /><small className="mt-1 block text-xs text-muted-foreground">Zero significa ilimitado.</small></label><label className="text-sm font-extrabold">Expira em<input name="expiresAt" type="date" className={field} /></label><label className="text-sm font-extrabold sm:col-span-2">Planos permitidos<input name="planIds" placeholder="pro, premium — vazio aceita qualquer plano" className={field} /></label></div><div className="flex flex-wrap gap-5"><label className="flex items-center gap-2 text-sm font-extrabold"><input type="checkbox" name="active" defaultChecked className="h-4 w-4 accent-primary" />Cupom ativo</label><label className="flex items-center gap-2 text-sm font-extrabold"><input type="checkbox" name="monthly" defaultChecked className="h-4 w-4 accent-primary" />Mensal</label><label className="flex items-center gap-2 text-sm font-extrabold"><input type="checkbox" name="annual" defaultChecked className="h-4 w-4 accent-primary" />Anual</label></div>{state.error && <p role="alert" className="text-sm font-extrabold text-destructive">{state.error}</p>}{state.success && <p role="status" className="text-sm font-extrabold text-primary">{state.success}</p>}<button disabled={pending} className="btn-pop gap-2 bg-primary px-5 text-xs text-primary-foreground shadow-[var(--shadow-pop)] disabled:opacity-60">{pending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Salvar cupom</button></form>;
}
