import { TicketPercent } from "lucide-react";
import { requirePermission } from "@/core/admin/admin-service";
import { listCoupons } from "@/core/payments/coupon-service";
import { CouponForm } from "./coupon-form";

const date = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "America/Bahia" });
export default async function CouponsPage() {
  await requirePermission("plans.manage");
  const coupons = await listCoupons();
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><header><div className="inline-flex rounded-full bg-primary/15 px-3 py-1 text-xs font-extrabold uppercase tracking-wider text-primary">Aquisição e retenção</div><h1 className="mt-3 text-4xl font-black">Cupons</h1><p className="mt-1 font-bold text-muted-foreground">Crie descontos com validade, limite de uso, plano e periodicidade.</p></header><CouponForm /><section className="card-pop overflow-hidden"><div className="grid grid-cols-[1fr_7rem] gap-3 border-b-2 border-border bg-muted/50 px-5 py-3 text-xs font-extrabold uppercase text-muted-foreground sm:grid-cols-[10rem_1fr_8rem_8rem_9rem]"><span>Código</span><span className="hidden sm:block">Descrição</span><span className="hidden sm:block">Desconto</span><span className="hidden sm:block">Usos</span><span>Status</span></div>{coupons.length ? <div className="divide-y-2 divide-border">{coupons.map((coupon) => <article key={coupon.code} className="grid grid-cols-[1fr_7rem] gap-3 px-5 py-4 sm:grid-cols-[10rem_1fr_8rem_8rem_9rem]"><strong className="text-primary">{coupon.code}</strong><span className="hidden text-sm font-bold text-muted-foreground sm:block">{coupon.description}</span><span className="hidden text-sm font-extrabold sm:block">{coupon.discountType === "percent" ? `${coupon.discountValue}%` : `R$ ${coupon.discountValue.toFixed(2).replace(".", ",")}`}</span><span className="hidden text-sm font-bold sm:block">{coupon.redemptions}/{coupon.maxRedemptions || "∞"}</span><span className={`text-xs font-extrabold ${coupon.active ? "text-primary" : "text-muted-foreground"}`}>{coupon.active ? coupon.expiresAt ? `Até ${date.format(new Date(coupon.expiresAt))}` : "Ativo" : "Inativo"}</span></article>)}</div> : <div className="grid place-items-center py-14 text-center"><TicketPercent className="h-9 w-9 text-muted-foreground/40" /><p className="mt-3 font-extrabold">Nenhum cupom cadastrado</p></div>}</section></main>;
}
