"use client";

import { useActionState, useState } from "react";
import { ImageUp, LoaderCircle, Save } from "lucide-react";
import type { SiteContent } from "@/core/admin/site-content-service";
import { updateSiteContentAction, type ContentActionState } from "./actions";

const field = "mt-1.5 h-11 w-full rounded-xl border-2 border-border bg-background px-3 text-sm font-bold outline-none focus:border-primary";
const area = `${field} h-auto py-3`;
export function ContentForm({ content }: { content: SiteContent }) {
  const [state, action, pending] = useActionState(updateSiteContentAction, {} as ContentActionState);
  return <form action={action} encType="multipart/form-data" className="space-y-6">
    <section className="card-pop space-y-5 p-5 sm:p-6"><div><h2 className="text-2xl font-black">SEO técnico</h2><p className="text-sm font-bold text-muted-foreground">Informações exibidas nos buscadores e compartilhamentos.</p></div><div className="grid gap-4 sm:grid-cols-2">
      <label className="text-sm font-extrabold sm:col-span-2">Título SEO<input name="seoTitle" defaultValue={content.seoTitle} required maxLength={70} className={field} /></label>
      <label className="text-sm font-extrabold sm:col-span-2">Meta descrição<textarea name="seoDescription" defaultValue={content.seoDescription} required maxLength={170} rows={3} className={area} /></label>
      <label className="text-sm font-extrabold sm:col-span-2">Palavras-chave<textarea name="seoKeywords" defaultValue={content.seoKeywords.join(", ")} required rows={3} className={area} /><small className="mt-1 block text-xs text-muted-foreground">Separe por vírgula ou linha.</small></label>
      <label className="text-sm font-extrabold sm:col-span-2">URL canônica<input name="canonicalUrl" type="url" defaultValue={content.canonicalUrl} required className={field} /></label>
    </div><label className="flex items-center gap-2 text-sm font-extrabold"><input type="checkbox" name="allowIndexing" defaultChecked={content.allowIndexing} className="h-4 w-4 accent-primary" />Permitir indexação nos buscadores</label></section>
    <section className="card-pop space-y-5 p-5 sm:p-6"><div><h2 className="text-2xl font-black">Identidade nos buscadores e redes sociais</h2><p className="text-sm font-bold text-muted-foreground">Envie arquivos otimizados em PNG, JPEG ou WebP, com até 3 MB.</p></div><div className="grid items-start gap-5 lg:grid-cols-2"><AssetUpload name="logoSquare" label="Logomarca quadrada" description="Recomendado: 512 × 512 px. Usada como identidade da marca para mecanismos de busca." currentUrl={content.logoSquareUrl} square /><AssetUpload name="socialImage" label="Capa de compartilhamento" description="Recomendado: 1200 × 630 px. Aparece ao compartilhar o link em redes sociais e mensageiros." currentUrl={content.socialImageUrl} /></div></section>
    <section className="card-pop space-y-5 p-5 sm:p-6"><div><h2 className="text-2xl font-black">Conteúdo da landing page</h2><p className="text-sm font-bold text-muted-foreground">Textos estratégicos da página pública.</p></div><div className="grid gap-4 sm:grid-cols-2">
      <label className="text-sm font-extrabold">Título principal<input name="heroTitle" defaultValue={content.heroTitle} required className={field} /></label><label className="text-sm font-extrabold">Trecho destacado<input name="heroHighlight" defaultValue={content.heroHighlight} required className={field} /></label>
      <label className="text-sm font-extrabold sm:col-span-2">Descrição principal<textarea name="heroDescription" defaultValue={content.heroDescription} required rows={3} className={area} /></label><label className="text-sm font-extrabold">CTA principal<input name="primaryCta" defaultValue={content.primaryCta} required className={field} /></label><label className="text-sm font-extrabold">CTA secundário<input name="secondaryCta" defaultValue={content.secondaryCta} required className={field} /></label><label className="text-sm font-extrabold sm:col-span-2">Prova social<input name="socialProof" defaultValue={content.socialProof} required className={field} /></label>
      <label className="text-sm font-extrabold">Etiqueta de recursos<input name="featuresEyebrow" defaultValue={content.featuresEyebrow} required className={field} /></label><label className="text-sm font-extrabold">Título de recursos<input name="featuresTitle" defaultValue={content.featuresTitle} required className={field} /></label><label className="text-sm font-extrabold sm:col-span-2">Descrição de recursos<textarea name="featuresDescription" defaultValue={content.featuresDescription} required rows={2} className={area} /></label>
      <label className="text-sm font-extrabold">Título de gamificação<input name="gamificationTitle" defaultValue={content.gamificationTitle} required className={field} /></label><label className="text-sm font-extrabold">Título de comunidade<input name="communityTitle" defaultValue={content.communityTitle} required className={field} /></label><label className="text-sm font-extrabold">Descrição de gamificação<textarea name="gamificationDescription" defaultValue={content.gamificationDescription} required rows={3} className={area} /></label><label className="text-sm font-extrabold">Descrição de comunidade<textarea name="communityDescription" defaultValue={content.communityDescription} required rows={3} className={area} /></label>
      <label className="text-sm font-extrabold">Título dos depoimentos<input name="testimonialsTitle" defaultValue={content.testimonialsTitle} required className={field} /></label><label className="text-sm font-extrabold">Título dos preços<input name="pricingTitle" defaultValue={content.pricingTitle} required className={field} /></label><label className="text-sm font-extrabold sm:col-span-2">Descrição dos preços<input name="pricingDescription" defaultValue={content.pricingDescription} required className={field} /></label><label className="text-sm font-extrabold sm:col-span-2">Texto do rodapé<input name="footerText" defaultValue={content.footerText} required className={field} /></label>
    </div></section>
    {state.error && <p role="alert" className="text-sm font-extrabold text-destructive">{state.error}</p>}{state.success && <p role="status" className="text-sm font-extrabold text-primary">{state.success}</p>}<button disabled={pending} className="btn-pop gap-2 bg-primary px-6 text-xs text-primary-foreground shadow-[var(--shadow-pop)] disabled:opacity-60">{pending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Publicar alterações</button>
  </form>;
}

function AssetUpload({ name, label, description, currentUrl, square = false }: { name: "logoSquare" | "socialImage"; label: string; description: string; currentUrl: string; square?: boolean }) {
  const [preview, setPreview] = useState(currentUrl);
  const [dimensions, setDimensions] = useState("");
  return <div className="rounded-2xl border-2 border-border bg-muted/25 p-4"><div className={`${square ? "aspect-square max-w-56" : "aspect-[1200/630]"} mx-auto w-full overflow-hidden rounded-xl border-2 border-border bg-card bg-contain bg-center bg-no-repeat`} style={{ backgroundImage: `url("${preview}")` }} /><h3 className="mt-4 font-extrabold">{label}</h3><p className="mt-1 text-xs font-bold text-muted-foreground">{description}</p>{dimensions && <p className="mt-2 text-xs font-extrabold text-primary">Arquivo selecionado: {dimensions}</p>}<input type="hidden" name={`${name}Url`} value={currentUrl} /><label className="btn-pop mt-4 cursor-pointer gap-2 bg-muted px-4 py-2 text-xs shadow-[var(--shadow-pop-muted)]"><ImageUp className="h-4 w-4" />Selecionar imagem<input type="file" name={`${name}File`} accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; const url = URL.createObjectURL(file); setPreview(url); const image = new Image(); image.onload = () => setDimensions(`${image.naturalWidth} × ${image.naturalHeight} px`); image.src = url; }} /></label></div>;
}
